theme: jekyll-theme-minimal
title: Rudy Duran # your name (or website title) here
logo: "/images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science | Business Intelligence | Data Analytics
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/carly-taylor0017/">LinkedIn</a>
  <br>
  <br>
